url: http://legal-united.com
baseurl: 

# Site settings
title: Legal United
email: info@legal-united.com
phone: 06000000
description: "I'm Jantine de Bree. A lawyer based in Amsterdam. Let me help you manage your Intellectual Property and terms and conditions."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4682B4
  secondary: b0732e
  secondary-dark: 333
  secondary-light: FFF

# Team names, titles and social links
people:
- name: Jantine de Bree
  pic: 1
  position: Lawyer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: https://nl.linkedin.com/in/jantine-de-bree-abb755112/en

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: linkedin
    url: https://nl.linkedin.com/in/jantine-de-bree-abb755112/en

# Postal address (add as many lines as necessary)
address:
  - line: Prinsengracht
  - line: Amsterdam, The Netherlands

# Build settings
markdown: kramdown
permalink: pretty
